FROM node:12
WORKDIR /usr/src/app
RUN npm install -g create-react-app

# RUN npm install react @types/react react-dom @types/react-dom axios @types/axios

# RUN create-react-app react-basic
# RUN create-react-app react-basic --template typescript
