version: '3'

services:
  react:
    container_name: udemy-react
    tty: true
    build:
        context: .
        dockerfile: Dockerfile.React
    volumes:
        - ./client/:/usr/src/app
    ports:
    - "3000:3000"
    tty: true

  django:
    container_name: udemy-django
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.Django
    environment:
        DJANGO_MODWSGI_EXTRA_ARGS: ""
        ALLOWED_HOSTS: '*'
        DATABASE_ENGINE: django.db.backends.postgresql
        DATABASE_DB: django_db
        DATABASE_USER: admin
        DATABASE_PASSWORD: admin
        DATABASE_HOST: udmey-postgres
        DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/code
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: udmey-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

#   nginx:
#     container_name: udemy-proxy
#     image: nginx:stable-alpine
#     depends_on:
#       - django
#       - react
#     environment:
#       PROXY_HOST: localhost
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./nginx/conf:/etc/nginx/conf.d
#       - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
#       - ./client/static:/static
#     command: /bin/sh -c "envsubst '$$PROXY_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

# # トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data: